//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tdtlession07.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TdtKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TdtKhoa()
        {
            this.tdtSinhVien = new HashSet<tdtSinhVien>();
        }
    
        public string TdtMaKH { get; set; }
        public string TdtTenKH { get; set; }
        public Nullable<bool> TdtTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tdtSinhVien> tdtSinhVien { get; set; }
    }
}
