//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tdtlession07.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdtSinhVien
    {
        public string TdtMaSV { get; set; }
        public string TdtHoSV { get; set; }
        public string TdtTenSV { get; set; }
        public Nullable<System.DateTime> TdtNgaySinh { get; set; }
        public Nullable<bool> TdtPhai { get; set; }
        public string TdtPhone { get; set; }
        public string TdtEmail { get; set; }
        public string TdtMaKH { get; set; }
    
        public virtual TdtKhoa TdtKhoa { get; set; }
    }
}
